server:
  port: 8083
  servlet:
    session:
      timeout: 15000
#redis
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: 60
        max-idle: 8
        min-idle: 0
    timeout: 10000
logging:
  level:
    root: info